@host = http://localhost:9090/api
@uri = {{host}}/citas
@token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjaXRhcy1tZWRpY2FzLWJ1c2luZXNzIiwiaWF0IjoxNzkwNzEzNDI5LCJleHAiOjE3OTA3MTcwMjksInN1YiI6IjEiLCJ1c2VybmFtZSI6Imx1bHV3ZXN0Iiwicm9sX2lkIjoyfQ.rB_Y4bycZyBZ82BfSMSrRhLQeapf4RK7f2iG6mF5rv4

GET {{uri}}/paciente/1
Authorization: Bearer {{token}}
###

GET {{uri}}/medico/1
Authorization: Bearer {{token}}
###

POST {{uri}}
#Authorization: Bearer {{token}}
Content-Type: application/json

 {
    "paciente_id": 1,
    "medico_id": 2,
    "fecha_hora": "2026-10-15 10:00:00",
    "motivo" : "Consulta de dolor lumbar"
  }
###

