@host = http://localhost:9090/api
@uri = {{host}}/citas
@token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjaXRhcy1tZWRpY2FzLWJ1c2luZXNzIiwiaWF0IjoxNzkwNjk3MTkzLCJleHAiOjE3OTA3MDA3OTMsInN1YiI6IjIxIiwidXNlcm5hbWUiOiJsdWlzd2VzdDEiLCJyb2xfaWQiOjJ9.zwAwFqzISO0OlZX30jdUw0x0JyloBxH7X1xthnmDmWg

GET {{uri}}/paciente
Authorization: Bearer {{token}}
###

POST {{uri}}
#Authorization: Bearer {{token}}
Content-Type: application/json

 {
    "paciente_id": 1,
    "medico_id": 2,
    "fecha_hora": "2026-10-15 10:00:00",
    "motivo" : "Consulta de dolor lumbar"
  }
###

PUT {{uri}}/7
#Authorization: Bearer {{token}}
Content-Type: application/json

 {
    "nombre_completo": "Luis Aramando West Grant",
    "telefono": "8888-7772"
  }
###
DELETE {{uri}}/1
###

GET {{uri}}/filter/0/10?nombre=lu&cedula=&especialidad=car
#Authorization: Bearer {{token}} 