@host = http://localhost:9090/api
@uri = {{host}}/medicos
@token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjaXRhcy1tZWRpY2FzLWJ1c2luZXNzIiwiaWF0IjoxNzkwMzEwNDY5LCJleHAiOjE3OTAzMTA1MTQsInN1YiI6IjIwIiwidXNlcm5hbWUiOiJtYWlrd2VzMSIsInJvbF9pZCI6Mn0.-VFyrh9_tN8bJ84LRKLdk8C4rmh_JiMjyPrmwDDol4w

GET {{uri}}
Authorization: Bearer {{token}}
###

POST {{uri}}
#Authorization: Bearer {{token}}
Content-Type: application/json

 {
    "especialidad_id": 1,
    "nombre_completo": "Maikol West Gr",
    "licencia": "LIC-1234501",
    "telefono": "",
    "username": "maikwes1",
    "password": "secure1D#"
  }
###

PUT {{uri}}/3
#Authorization: Bearer {{token}}
Content-Type: application/json

 {
    "nombre_completo": "Armando West Grant",
    "telefono": "8686-5555"
  }
###
DELETE {{uri}}/6
###

GET {{uri}}/filter/0/10?nombre=&cedula=&especialidad=
#Authorization: Bearer {{token}} 
###

POST http://localhost:9090/api/auth/login
Content-Type: application/json

{
    "username": "maikwes1",
    "password": "secure1D#"
}