@host = http://localhost:9090/api
@uri = {{host}}/medicos
#@token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJsb2NhbGhvc3QiLCJpYXQiOjE3Nzg0MzE2NjQsImV4cCI6MTc3ODQzMzQ2NCwic3ViIjoiNy0xMjM0LTU2NzgiLCJyb2wiOjMsIm5vbSI6Ikx1aXMgV2VzdCJ9.kPq1MSyAXEKDX9hfJRc_9SmJqexUI08fBDolaQfwH7E

GET {{uri}}

#Authorization: Bearer {{token}}
###

POST {{uri}}
#Authorization: Bearer {{token}}
Content-Type: application/json

 {
    "especialidad_id": 1,
    "nombre_completo": "Maikol West Grant",
    "licencia": "LIC-123450",
    "telefono": "8888-7771",
    "username": "maikwest",
    "password": "securepassword"
  }
###

PUT {{uri}}/3
#Authorization: Bearer {{token}}
Content-Type: application/json

 {
    "nombre_completo": "Armando West Grant",
    "telefono": "8686-5555"
  }
###
DELETE {{uri}}/6
###

GET {{uri}}/filter/0/10?nombre=&cedula=&especialidad=
#Authorization: Bearer {{token}} 