@startwbs arbol
* frontend_web/
** src/
*** app/
**** app.config.ts
**** app.css
**** app.html
**** app.routes.ts
**** app.spec.ts
**** app.ts
**** components/
***** home/
***** medico/
***** paciente/
***** especialidad/
***** citas/
***** change-passw/
***** forms/
****** dialogo-general/
****** frm-cliente/
****** frm-login/
****** frm-passw/
***** error401/
***** error403/
***** loading-compmonent/
***** login/
**** shared/
***** helpers/
****** guards/
******* auth-guard.ts
******* login-guard.ts
****** interceptors/
******* jwt-interceptor.ts
******* loading-interceptor.ts
******* refresh-interceptor.ts
****** interfaces/
******* iToken.ts
******* login-form.ts
******* roles.ts
******* tipo-medico.ts
****** validators/
******* passw-validator.ts
***** models/
****** User.ts
****** Medico.ts
****** Paciente.ts
****** Especialidad.ts
****** Cita.ts
***** services/
****** auth.service.ts
****** medico.service.ts
****** paciente.service.ts
****** especialidad.service.ts
****** citas.service.ts
****** loading-service.ts
****** print-service.ts
****** tokens.service.ts
****** usuario.service.ts
**** environments/
***** environment.development.ts
***** environment.ts
*** index.html
*** main.ts
*** material-theme.scss
*** styles.css
@endwbs